a에 1의 값을 넣고, a의 type을 print한다. a의 type은 int가 나오는데 integer의 줄임말임.

In [2]:
a = 1; print(type(a))

<class 'int'>


float(x)는 x를 소수점이 있는 수로 변환하는 함수. a를 소수점이 있는 숫자로 변환하고 a의 타입을 프린트한다. float화 되었기 때문에 float가 나온다.

In [3]:
a = 1; a = float(a); print(type(a))

<class 'float'>


a에 1.2의 값을 넣는다. int(x)는 정수로 변환하는 함수. a를 정수로 변환하고 type을 print하면 int가 나온다.

In [8]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


1.2를 정수화시킨 값은 무엇일지 궁금해서 a만 print해보았다. 1.2에서 0.2를 버린 1이 나왔다!

In [10]:
a

1

a에 '123'이라는 값을 넣는다. '123'은 백이십삼이 아니라 문자열이다. 문자열의 type은 string을 줄여서 str이라고 함. a[1]은 1의 문자열중 두번째 값을 프린트하는 것이다. '123'의 제일 왼쪽부터 0번째, 1번째, 2번째 순이다. (0부터 시작하는것을 유의할 것!)

In [11]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


list는 순서가 있는 자료열이다. '123'이라는 문자열을 자료열로 만들어서 a의 타입을 print하면 list가 나온다. a[2]는 a라는 자료열의 자료들 중 왼쪽부터 세번째에 있는 값이다!

In [12]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


list의 string 변환이 가능할까...? -> 변화가 없다..

In [14]:
a = str(a); print(a)

['1', '2', '3']


이런식으로 list안에 list를 구성할 수도 있다. 자료열안에 자료열! [3, '4'] 라는 자료 자체가 a의 세번째 자료값이기 때문에 a[2]는 [3, '4']가 나온다. 이처럼 list라는 자료열은 다양한 자료형들을 담을 수 있다.

In [15]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


소괄호로 묶여있는 자료열은 tuple이라고 한다. list와 거의 흡사함.

In [16]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


중괄호로 묶여있는 dictionary. key와 각 key에 해당하는 value가 존재한다. print(a[a])는 a라는 dic안의 a라는 key의 value를 프린트하라는 말이다. apple이 나온다!

In [17]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


list 자료열의 자료값으로 tuple을 넣을 수도 있다! 
행렬과 비슷한 모양의 a를 만들었다.

In [18]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

array는 matrix 비슷한 것이라고 생각하면 됨. numpy.ndarray: numpy라는 폴더의 n dimension array이다.

In [20]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


b가 matrix라면 b* b가 불가능한 수식일텐데 array라서 계산이 되었다. 

In [22]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


np.matrix(b)라는 함수를 활용해서 array였던 b를 matrix로 변환해주었다.

In [24]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


c는 2행 3열의 matrix이다. c* c는 불가능한 수식. 

In [25]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

c.T는 c를 transpose해주는 것이다. 따라서 그 결과값으로 2행 2열의 matrix가 나온다

In [26]:
c*c.T

matrix([[14, 19],
        [19, 73]])